apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: istio-playground
  namespace: metallb-system
spec:
  addresses:
  - 172.18.255.200-172.18.255.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: istio-playground
  namespace: metallb-system